### ISSUE TITLE
great first post

### ISSUE THREAD

**Issue by mpizenberg** [matheus23/irreactive.com#1]
Hi, that first post was an interesting read (https://github.com/matheus23/irreactive.com/blob/master/content/declarative-apis.md). 

There are few typos like "cicle", a lot of "moveTo" instead of "moved".

Also, the sentence "And this type analysis happens at compile time, so you'll know there's something wrong before you run your code with actual data" feels a bit weird at its position.

Regarding functional programming for UI, I suppose you already read Evan's thesis about functional reactive programming and the birth of Elm. If not, it's an interesting read. The survey by Bainomugisha on reactive programming is also an interesting read.

**Comment by matheus23** [comment]
Thanks @mpizenberg !

> I suppose you already read Evan's thesis about functional reactive programming and the birth of Elm
Yes, it's a great thesis.

> The survey by Bainomugisha on reactive programming is also an interesting read.
That one is new to me!

We (my brother & friends) have been experimenting with FRP since before Elm, but had very limited success building user interfaces with it - much like evan.
Maybe this could be a topic for another post: "Why FRP doesn't work", but generally I'm trying to write more about what worked than what didn't work.
